#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-jessedyck-sitebuildinga-0ew263y51pd.ws-us108.gitpod.io
- 8025-jessedyck-sitebuildinga-0ew263y51pd.ws-us108.gitpod.io
- 8036-jessedyck-sitebuildinga-0ew263y51pd.ws-us108.gitpod.io
